#!/usr/bin/python

import sys
import subprocess
import os

gcChoices = [
  ["-XX:+UseG1GC"],
  ["-XX:+UseParallelGC"],
  ["-XX:+UseParallelGC", "-XX:+UseCondCardMark"],
  []
]

def setGC(gcConfig):
  return gcChoices[gcConfig]

def setProcs(numProcs):
  return []
  #return ["-Djava.util.concurrent.ForkJoinPool.common.parallelism={}".format(numProcs)]

def makeCmd(gcConfig, numProcs):
  progArgs = ["Main", "10000000", "200", "5"]
  runtimeArgs = setGC(gcConfig) + setProcs(numProcs)
  return ["/usr/bin/java"] + runtimeArgs + progArgs

#numProcs = int(sys.argv[1])
numProcs = 72 # actually doesn't matter now, java should pick all of them
gcConfigNum = 0
if len(sys.argv) > 1:
  gcConfigNum = int(sys.argv[1])
cmd = makeCmd(gcConfigNum, numProcs)

print(" ".join(cmd))

subprocess.call(" ".join(cmd), shell=True)

# output = subprocess.check_output(cmd)
# print(output)
