.PHONY: phony

default: Reduce

Tabulate: *.java
	javac Runner.java Tabulate.java
Filter: *.java
	javac Runner.java Filter.java
Reduce: *.java
	javac Runner.java Reduce.java


clean: phony
	rm -f *.class